<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class AuthData extends Seeder
{
    public function run()
    {
        $data = [
            [
                'user_id' => generate_uuid(),
                'user_name' => 'admin',
                'user_password' => password_hash('admin123', PASSWORD_DEFAULT),
                'full_name' => 'Super Administrator',
                'user_email' => enkripsi('priyo.ardy@yahoo.com'),
                'email_hash' => email_hash('priyo.ardy@yahoo.com'),
                'user_phone' => enkripsi('081234567890'),
                'phone_hash' => phone_hash('081234567890'),
                'user_status' => '1',
                'user_level' => '0',
                'user_image' => 'default.png',
                'attempts' => 0,
                'remark' => 'From database seeder',
                'last_login' => null,
                'login_from' => '',
                'user_agent' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'created_by' => 'admin',
                'updated_at' => date('Y-m-d H:i:s'),
                'updated_by' => '',
                'deleted_at' => null,
            ],
            [
                'user_id' => generate_uuid(),
                'user_name' => 'user',
                'user_password' => password_hash('user123', PASSWORD_DEFAULT),
                'full_name' => 'User',
                'user_email' => enkripsi('priyo.ardy@gmail.com'),
                'email_hash' => email_hash('priyo.ardy@gmail.com'),
                'user_phone' => enkripsi('085678901234'),
                'phone_hash' => phone_hash('085678901234'),
                'user_status' => '1',
                'user_level' => '2',
                'user_image' => 'default.png',
                'attempts' => 0,
                'remark' => 'From database seeder',
                'last_login' => null,
                'login_from' => '',
                'user_agent' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'created_by' => 'admin',
                'updated_at' => date('Y-m-d H:i:s'),
                'updated_by' => '',
                'deleted_at' => null,
            ],
            [
                "user_id" => "34e62680-1906-4776-9b1e-e744a9342123",
                "user_name" => "0004",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Wahyu Jatmiko",
                "user_email" => enkripsi('wahyu.jatmmiko@schlemmer.co.id'),
                "email_hash" => email_hash('wahyu.jatmmiko@schlemmer.co.id'),
                "user_phone" => enkripsi('000'),
                "phone_hash" => phone_hash('000'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "24720104-0380-4555-81c4-7336bafb80c6",
                "user_name" => "0006",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Adnan Khasogi",
                "user_email" => enkripsi('adnan.khasogi@schlemmer.co.id'),
                "email_hash" => email_hash('adnan.khasogi@schlemmer.co.id'),
                "user_phone" => enkripsi('001'),
                "phone_hash" => phone_hash('001'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "9c22b1a8-1fd2-43b7-87bd-54812c5089dd",
                "user_name" => "0011",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Nanang Yuliatmoko",
                "user_email" => enkripsi('nanang.yuliatmoko@schlemmer.co.id'),
                "email_hash" => email_hash('nanang.yuliatmoko@schlemmer.co.id'),
                "user_phone" => enkripsi('002'),
                "phone_hash" => phone_hash('002'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "57d24725-ce0a-4e62-b97c-411a05e3e0c2",
                "user_name" => "0021",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Arif Muhammad Safi'i",
                "user_email" => enkripsi('arif.muhammad@schlemmer.co.id'),
                "email_hash" => email_hash('arif.muhammad@schlemmer.co.id'),
                "user_phone" => enkripsi('003'),
                "phone_hash" => phone_hash('003'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "9738968a-1efb-4194-95a6-b9d60886f5f7",
                "user_name" => "0078",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Ruliyanto",
                "user_email" => enkripsi('ruliyanto@schlemmer.co.id'),
                "email_hash" => email_hash('ruliyanto@schlemmer.co.id'),
                "user_phone" => enkripsi('004'),
                "phone_hash" => phone_hash('004'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "ecf22c89-4d62-40be-8eab-95c288b46f12",
                "user_name" => "0092",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Ardy Priyo Sudiyantoko",
                "user_email" => enkripsi('priyo.ardy@schlemmer.co.id'),
                "email_hash" => email_hash('priyo.ardy@schlemmer.co.id'),
                "user_phone" => enkripsi('005'),
                "phone_hash" => phone_hash('005'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "0",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "179536a0-1894-4825-a37c-dc14cf5d8666",
                "user_name" => "0103",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Selvia Wulandari",
                "user_email" => enkripsi('selvia.wulandari@schlemmer.co.id'),
                "email_hash" => email_hash('selvia.wulandari@schlemmer.co.id'),
                "user_phone" => enkripsi('006'),
                "phone_hash" => phone_hash('006'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "a6978631-f3b9-4d4f-928f-c215670ab0d2",
                "user_name" => "0107",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Prismawinda Afinindi",
                "user_email" => enkripsi('prismawinda.afinindi@schlemmer.co.id'),
                "email_hash" => email_hash('prismawinda.afinindi@schlemmer.co.id'),
                "user_phone" => enkripsi('007'),
                "phone_hash" => phone_hash('007'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "9188e64d-410f-410f-b321-0e535393746e",
                "user_name" => "0142",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Tian Bestiana",
                "user_email" => enkripsi('tian.bestiana@schlemmer.co.id'),
                "email_hash" => email_hash('tian.bestiana@schlemmer.co.id'),
                "user_phone" => enkripsi('008'),
                "phone_hash" => phone_hash('008'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "a4887897-eb04-42bd-af4b-dd914f34a4f8",
                "user_name" => "0199",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Erlina Desti Kusmawati",
                "user_email" => enkripsi('sales.admin@schlemmer.co.id'),
                "email_hash" => email_hash('sales.admin@schlemmer.co.id'),
                "user_phone" => enkripsi('009'),
                "phone_hash" => phone_hash('009'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "50d8b19c-ef8d-4573-b509-f55f09c6608b",
                "user_name" => "0280",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Nicky Putri Angela",
                "user_email" => enkripsi('nicky.putri@schlemmer.co.id'),
                "email_hash" => email_hash('nicky.putri@schlemmer.co.id'),
                "user_phone" => enkripsi('010'),
                "phone_hash" => phone_hash('010'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "da0dba10-b462-44f2-b58e-55d54c2cda1a",
                "user_name" => "0308",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Joko Prasetyo",
                "user_email" => enkripsi('joko.prasetyo@schlemmer.co.id'),
                "email_hash" => email_hash('joko.prasetyo@schlemmer.co.id'),
                "user_phone" => enkripsi('011'),
                "phone_hash" => phone_hash('011'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "aaa4bbe2-83ab-4b46-8a23-a072ed244e5d",
                "user_name" => "0347",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Nadila Isma Rizki Putri",
                "user_email" => enkripsi('nadila.isma@schlemmer.co.id'),
                "email_hash" => email_hash('nadila.isma@schlemmer.co.id'),
                "user_phone" => enkripsi('012'),
                "phone_hash" => phone_hash('012'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "f0a83eeb-7267-45e8-aa6a-848354ed466e",
                "user_name" => "0359",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Yusuf Fianto",
                "user_email" => enkripsi('yusuf.fianto@schlemmer.co.id'),
                "email_hash" => email_hash('yusuf.fianto@schlemmer.co.id'),
                "user_phone" => enkripsi('013'),
                "phone_hash" => phone_hash('013'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "07be0921-bccf-4429-a22e-2143f537bbec",
                "user_name" => "0381",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Wahyu Hidayatullah",
                "user_email" => enkripsi('wahyu.hidayatullah@schlemmer.co.id'),
                "email_hash" => email_hash('wahyu.hidayatullah@schlemmer.co.id'),
                "user_phone" => enkripsi('014'),
                "phone_hash" => phone_hash('014'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "4e56b69c-9ae8-4aa3-8ed2-31c12eabe7b6",
                "user_name" => "0443",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Bayu Saputri Wulandari",
                "user_email" => enkripsi('bayu.saputri.wulandari@schlemmer.co.id'),
                "email_hash" => email_hash('bayu.saputri.wulandari@schlemmer.co.id'),
                "user_phone" => enkripsi('015'),
                "phone_hash" => phone_hash('015'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "1198ad9e-5c91-47ba-b433-e7bd71fc0ebb",
                "user_name" => "0444",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Muhamad Taudihul La'ali",
                "user_email" => enkripsi('muhamad.taudihul@schlemmer.co.id'),
                "email_hash" => email_hash('muhamad.taudihul@schlemmer.co.id'),
                "user_phone" => enkripsi('016'),
                "phone_hash" => phone_hash('016'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "908b4dbc-5205-42e8-a4ef-f514ab1e70b6",
                "user_name" => "0447",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Yakub Guno Wibowo",
                "user_email" => enkripsi('yakub.guno@schlemmer.co.id'),
                "email_hash" => email_hash('yakub.guno@schlemmer.co.id'),
                "user_phone" => enkripsi('017'),
                "phone_hash" => phone_hash('017'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ],
            [
                "user_id" => "49bc5a82-12cc-4c5c-b06d-6d59f853d173",
                "user_name" => "0486",
                "user_password" => password_hash('123456', PASSWORD_DEFAULT),
                "full_name" => "Rizki Nur Ichsan",
                "user_email" => enkripsi('rizki.nur@schlemmer.co.id'),
                "email_hash" => email_hash('rizki.nur@schlemmer.co.id'),
                "user_phone" => enkripsi('018'),
                "phone_hash" => phone_hash('018'),
                "user_status" => "1",
                "user_image" => "default.png",
                "attempts" => "0",
                "user_level" => "1",
                "remark" => null,
                "last_login" => null,
                "login_from" => null,
                "user_agent" => null,
                "created_at" => date("Y-m-d H:i:s"),
                "created_by" => "admin",
                "updated_at" => date("Y-m-d H:i:s"),
                "updated_by" => "",
                "deleted_at" => null
            ]
        ];

        $this->db->table('m_user_auth')->insertBatch($data);
    }
}
