<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CustomerData extends Seeder
{
    public function run()
    {
        $data = [
            [
                "id" => "d468d020-c8b1-4cec-85c5-98931b5621f4",
                "code" => "CUST-000001",
                "name" => "Ningbo Schlemmer Automotive Parts Co.,Ltd",
                "address" => null,
                "email" => null,
                "email_hash" => null,
                "phone" => null,
                "phone_hash" => null,
                "contact_person" => null,
                "contact_person_phone" => null,
                "contact_person_phone_hash" => null,
                "contact_person_email" => null,
                "contact_person_email_hash" => null,
                "remark" => null,
                "created_at" => "2025-11-10 11:26:01",
                "created_by" => "admin",
                "updated_at" => "2025-11-10 11:26:01",
                "updated_by" => null,
                "deleted_at" => null
            ],
            [
                "id" => "99ae6260-3a30-40ab-b764-0c79b8996103",
                "code" => "CUST-000002",
                "name" => "Schlemmer Japan Co., Ltd.",
                "address" => null,
                "email" => null,
                "email_hash" => null,
                "phone" => null,
                "phone_hash" => null,
                "contact_person" => null,
                "contact_person_phone" => null,
                "contact_person_phone_hash" => null,
                "contact_person_email" => null,
                "contact_person_email_hash" => null,
                "remark" => null,
                "created_at" => "2025-11-10 11:26:01",
                "created_by" => "admin",
                "updated_at" => "2025-11-10 11:26:01",
                "updated_by" => null,
                "deleted_at" => null
            ],
            [
                "id" => "352ed187-d934-42d4-baae-6b42efc628b4",
                "code" => "CUST-000003",
                "name" => "Schlemmer Philippines Inc.",
                "address" => null,
                "email" => null,
                "email_hash" => null,
                "phone" => null,
                "phone_hash" => null,
                "contact_person" => null,
                "contact_person_phone" => null,
                "contact_person_phone_hash" => null,
                "contact_person_email" => null,
                "contact_person_email_hash" => null,
                "remark" => null,
                "created_at" => "2025-11-10 11:26:01",
                "created_by" => "admin",
                "updated_at" => "2025-11-10 11:26:01",
                "updated_by" => null,
                "deleted_at" => null
            ],
            [
                "id" => "a6d81af0-c668-45ae-86ce-0abf2992c468",
                "code" => "CUST-000004",
                "name" => "VietNam Schlemmer Automotive Parts Co.,Ltd",
                "address" => null,
                "email" => null,
                "email_hash" => null,
                "phone" => null,
                "phone_hash" => null,
                "contact_person" => null,
                "contact_person_phone" => null,
                "contact_person_phone_hash" => null,
                "contact_person_email" => null,
                "contact_person_email_hash" => null,
                "remark" => null,
                "created_at" => "2025-11-10 11:26:01",
                "created_by" => "admin",
                "updated_at" => "2025-11-10 11:26:01",
                "updated_by" => null,
                "deleted_at" => null
            ],
            [
                "id" => "7e055a34-59c7-45f2-bbf8-4bf671072de8",
                "code" => "CUST-000005",
                "name" => "Zhongshan Schlemmer Automotive Parts Co., Ltd.",
                "address" => null,
                "email" => null,
                "email_hash" => null,
                "phone" => null,
                "phone_hash" => null,
                "contact_person" => null,
                "contact_person_phone" => null,
                "contact_person_phone_hash" => null,
                "contact_person_email" => null,
                "contact_person_email_hash" => null,
                "remark" => null,
                "created_at" => "2025-11-10 11:26:01",
                "created_by" => "admin",
                "updated_at" => "2025-11-10 11:26:01",
                "updated_by" => null,
                "deleted_at" => null
            ],
            [
                "id" => "1a69379a-e579-42b9-ab7f-b11b232c0f03",
                "code" => "CUST-000006",
                "name" => "PT. Autocomp System Indonesia",
                "address" => null,
                "email" => null,
                "email_hash" => null,
                "phone" => null,
                "phone_hash" => null,
                "contact_person" => null,
                "contact_person_phone" => null,
                "contact_person_phone_hash" => null,
                "contact_person_email" => null,
                "contact_person_email_hash" => null,
                "remark" => null,
                "created_at" => "2025-11-10 11:26:01",
                "created_by" => "admin",
                "updated_at" => "2025-11-10 11:26:01",
                "updated_by" => null,
                "deleted_at" => null
            ],
            [
                "id" => "04997947-5405-44a5-8416-4b5b7952e776",
                "code" => "CUST-000007",
                "name" => "PT. Sumi Indo Wiring Systems",
                "address" => null,
                "email" => null,
                "email_hash" => null,
                "phone" => null,
                "phone_hash" => null,
                "contact_person" => null,
                "contact_person_phone" => null,
                "contact_person_phone_hash" => null,
                "contact_person_email" => null,
                "contact_person_email_hash" => null,
                "remark" => null,
                "created_at" => "2025-11-10 11:26:01",
                "created_by" => "admin",
                "updated_at" => "2025-11-10 11:26:01",
                "updated_by" => null,
                "deleted_at" => null
            ],
            [
                "id" => "180910f0-b77c-4b3f-ad75-0c580ac5a860",
                "code" => "CUST-000008",
                "name" => "PT. Misawa Trading Indonesia",
                "address" => null,
                "email" => null,
                "email_hash" => null,
                "phone" => null,
                "phone_hash" => null,
                "contact_person" => null,
                "contact_person_phone" => null,
                "contact_person_phone_hash" => null,
                "contact_person_email" => null,
                "contact_person_email_hash" => null,
                "remark" => null,
                "created_at" => "2025-11-10 11:26:01",
                "created_by" => "admin",
                "updated_at" => "2025-11-10 11:26:01",
                "updated_by" => null,
                "deleted_at" => null
            ],
            [
                "id" => "85258029-4c42-4bd2-b390-b271abe57ccf",
                "code" => "CUST-000009",
                "name" => "Sumitomo Electric Automotive Products",
                "address" => null,
                "email" => null,
                "email_hash" => null,
                "phone" => null,
                "phone_hash" => null,
                "contact_person" => null,
                "contact_person_phone" => null,
                "contact_person_phone_hash" => null,
                "contact_person_email" => null,
                "contact_person_email_hash" => null,
                "remark" => null,
                "created_at" => "2025-11-10 11:26:01",
                "created_by" => "admin",
                "updated_at" => "2025-11-10 11:26:01",
                "updated_by" => null,
                "deleted_at" => null
            ],
            [
                "id" => "6382ff58-0e12-40a4-aa83-6661e2bb101c",
                "code" => "CUST-000010",
                "name" => "PT. Kudami Teknologi Utama",
                "address" => null,
                "email" => null,
                "email_hash" => null,
                "phone" => null,
                "phone_hash" => null,
                "contact_person" => null,
                "contact_person_phone" => null,
                "contact_person_phone_hash" => null,
                "contact_person_email" => null,
                "contact_person_email_hash" => null,
                "remark" => null,
                "created_at" => "2025-11-10 11:26:01",
                "created_by" => "admin",
                "updated_at" => "2025-11-10 11:26:01",
                "updated_by" => null,
                "deleted_at" => null
            ],
            [
                "id" => "991537bb-4c0b-4a68-a870-b128e0bf888d",
                "code" => "CUST-000011",
                "name" => "PT. Abimanyu Sekar Nusantara",
                "address" => null,
                "email" => null,
                "email_hash" => null,
                "phone" => null,
                "phone_hash" => null,
                "contact_person" => null,
                "contact_person_phone" => null,
                "contact_person_phone_hash" => null,
                "contact_person_email" => null,
                "contact_person_email_hash" => null,
                "remark" => null,
                "created_at" => "2025-11-10 11:26:01",
                "created_by" => "admin",
                "updated_at" => "2025-11-10 11:26:01",
                "updated_by" => null,
                "deleted_at" => null
            ],
        ];

        $this->db->table('m_customer')->insertBatch($data);
    }
}
